

name: Build and deploy Python app to Azure Web App - UltimatePOS

on:
  push:
    branches:
      - demo
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r django_pos/requirements.txt
      - name: Run Tests
        run: |
          python django_pos/manage.py test
      - name: Run Checks
        run: |
          python django_pos/manage.py check
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A0DFD3A510CC4346B32603364840E1F8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_487120BE19CB45E49C18BDC43927D75E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7BAE26888562453DAA2C1C9E3CD690D5 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'UltimatePOS'
          slot-name: 'Production'
          
